import {useState} from 'react';
import {Button, Notice} from './UI';
import {post, csv, download, friendlyDate, type Plan, type Result} from './data';
import BulkInventory, {type InventoryDraft} from './BulkInventory';

type Entry = {stock:string; lead:string; pack:string; minimum:string; incoming:InventoryDraft['incoming']};
export default function StoreRestock({result,jobId,saved,onSave,onAddData}:{result:Result;jobId:string|null;saved:Record<string,Plan>;onSave:(plans:Record<string,Plan>)=>Promise<void>;onAddData:()=>void}) {
 const [date,setDate]=useState(result.forecast_start),[lead,setLead]=useState('5'),[days,setDays]=useState('7'),[buffer,setBuffer]=useState('2');
 const [entries,setEntries]=useState<Record<string,Entry>>(()=>Object.fromEntries(result.products.map(p=>{const a=saved[p.product_id]?.assumptions;return [p.product_id,{stock:String(a?.stock ?? (result.quality.config.synthetic?20:'')),lead:String(a?.lead_days ?? ''),pack:String(a?.pack_size ?? 1),minimum:String(a?.minimum_order ?? 0),incoming:(a?.incoming as Entry['incoming'])||[]}];})));
 const [plans,setPlans]=useState(saved),[errors,setErrors]=useState<Record<string,string>>({}),[dirty,setDirty]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState('');
 const changed=(id?:string)=>{setDirty(new Set(id?[...dirty,id]:result.products.map(p=>p.product_id)));setConfirmed(false);setMessage('');};
 const edit=(id:string,k:keyof Entry,v:unknown)=>{setEntries(prev=>({...prev,[id]:{...prev[id],[k]:v}}));changed(id);};
 function status(id:string,eligible:boolean|undefined) {if(dirty.has(id)&&plans[id])return 'Needs recalculation';if(errors[id])return errors[id];if(!eligible)return 'Forecast needs more reliable data';if(entries[id].stock.trim()==='')return 'Add stock count';if(!plans[id])return 'Ready to calculate';return plans[id].pre_arrival_unmet_units>0?'May run out before delivery':plans[id].suggested_order_units>0?'Order more':'Enough stock';}
 async function calculate(){setBusy(true);setMessage('');const next:Record<string,Plan>={};const problems:Record<string,string>={};try{for(const p of result.products){const e=entries[p.product_id];if(!p.inventory_eligible)continue;if(!e.stock.trim()){problems[p.product_id]='Add stock count';continue;}try{next[p.product_id]=await post<Plan>(`/jobs/${jobId}/inventory`,{product_id:p.product_id,stock:Number(e.stock),snapshot_date:date,lead_days:Number(e.lead||lead),review_days:Number(days),buffer_days:Number(buffer),pack_size:Number(e.pack),minimum_order:Number(e.minimum),incoming:e.incoming,mode:'historical_replay',confirmed:true});}catch(error){problems[p.product_id]=(error as Error).message;}}setPlans(next);setErrors(problems);setDirty(new Set());setMessage(`${Object.keys(next).length} products calculated. Check any rows that need attention.`);}finally{setBusy(false);}}
 const ordered=[...result.products].sort((a,b)=>(plans[b.product_id]?.pre_arrival_unmet_units||0)-(plans[a.product_id]?.pre_arrival_unmet_units||0)||(plans[b.product_id]?.suggested_order_units||0)-(plans[a.product_id]?.suggested_order_units||0));
 const validPlans=Object.fromEntries(Object.entries(plans).filter(([id])=>!dirty.has(id)));
 function exportSheet(){download(`restock-list-${result.forecast_start}.csv`,csv([['Product','Product ID','Stock available','Suggested order (units)','Delivery date','Status','Plan date','Delivery days','Days after delivery','Extra days'],...ordered.map(p=>{const plan=validPlans[p.product_id];return [p.name,p.product_id,entries[p.product_id].stock,plan?.suggested_order_units??'',plan?friendlyDate(plan.arrival_date):'',status(p.product_id,p.inventory_eligible),friendlyDate(plan?.planning_date||date),plan?.assumptions.lead_days??(entries[p.product_id].lead||lead),plan?.assumptions.review_days??days,plan?.assumptions.buffer_days??buffer];})]));}
 return <section className="store-restock">
  <div className="restock-heading"><h2>Your store’s restock list</h2><p className="muted">Add stock counts, calculate once, then download or print the whole list.</p></div>
  {!jobId&&<Notice>Saved results are shown below. Upload the sales files again to calculate a new plan.</Notice>}
  {result.quality.config.synthetic&&<Notice>Example stock counts are filled in. Change them to explore different plans.</Notice>}
  <div className="restock-edit-area">
  {jobId&&<fieldset disabled={busy} className="restock-fields"><BulkInventory jobId={jobId} onImport={items=>{if(Object.values(items).some(v=>v.snapshot_date!==date)) throw Error('The stock file date must match the stock count date shown above.');setEntries(prev=>{const next={...prev};for(const [id,v] of Object.entries(items)){if(next[id])next[id]={stock:String(v.stock??''),lead:String(v.lead_days??''),pack:String(v.pack_size??1),minimum:String(v.minimum_order??0),incoming:v.incoming||[]};}return next;});changed();setMessage('Stock counts imported. Check the table before calculating.');}}/></fieldset>}
  <p className="stock-date-note">This forecast starts on <strong>{friendlyDate(result.forecast_start)}</strong>. Use stock counts from that date. {result.forecast_start<new Date().toISOString().slice(0,10)&&<button className="text-link" onClick={onAddData}>Upload recent sales for a current plan</button>}</p>
  <fieldset disabled={busy||!jobId} className="restock-fields"><div className="inventory-grid">
   <label className="field">Stock counted on<input type="date" value={date} onChange={e=>{setDate(e.target.value);changed();}}/></label>
   <label className="field">Delivery takes (days)<input type="number" min="1" value={lead} onChange={e=>{setLead(e.target.value);changed();}}/></label>
   <label className="field">Days to cover after delivery<input type="number" min="1" value={days} onChange={e=>{setDays(e.target.value);changed();}}/></label>
  </div><details className="quiet-details"><summary>More options</summary><label className="field">Extra days of stock<input type="number" min="0" value={buffer} onChange={e=>{setBuffer(e.target.value);changed();}}/></label></details></fieldset></div>
  <p className="print-only">Forecast: {friendlyDate(result.forecast_start)} – {friendlyDate(result.forecast_end)}. Stock date: {friendlyDate(date)}. Default delivery: {lead} days; coverage after delivery: {days} days; extra stock: {buffer} days. Row details can override defaults. Suggested quantities are recommendations, not purchase orders.</p>
  <div className="table-scroll"><table className="restock-table"><thead><tr><th>Product</th><th>In stock</th><th>Order units</th><th>Delivery</th><th>Status</th><th className="restock-edit-area">Details</th></tr></thead><tbody>{ordered.map(p=>{const id=p.product_id,e=entries[id],plan=validPlans[id];return <tr key={id}><td><strong>{p.name}</strong><small>{id}</small></td><td><input className="restock-edit-area" aria-label={`Stock for ${p.name}`} type="number" min="0" step="1" disabled={busy||!jobId} value={e.stock} placeholder="Enter count" onChange={ev=>edit(id,'stock',ev.target.value)}/><span className="print-only">{e.stock||'—'}</span></td><td><strong>{plan?.suggested_order_units??'—'}</strong></td><td>{plan?friendlyDate(plan.arrival_date):'—'}</td><td>{status(id,p.inventory_eligible)}</td><td className="restock-edit-area"><details><summary>Edit details</summary><fieldset disabled={busy||!jobId} className="restock-fields">{(['lead','pack','minimum'] as const).map(k=><label className="field" key={k}>{k==='lead'?'Delivery days (blank uses shared setting)':k==='pack'?'Units per pack':'Minimum order'}<input type="number" min={k==='minimum'?0:1} value={e[k]} onChange={ev=>edit(id,k,ev.target.value)}/></label>)}<p>Stock already on its way</p>{e.incoming.map((o,i)=><div key={i}><label className="field">Arrival date<input type="date" value={o.date} onChange={ev=>edit(id,'incoming',e.incoming.map((x,j)=>j===i?{...x,date:ev.target.value}:x))}/></label><label className="field">Units<input type="number" min="1" value={o.units} onChange={ev=>edit(id,'incoming',e.incoming.map((x,j)=>j===i?{...x,units:Number(ev.target.value)}:x))}/></label><span>{o.status}</span><Button variant="text" onClick={()=>edit(id,'incoming',e.incoming.filter((_,j)=>j!==i))}>Remove</Button></div>)}<Button variant="text" onClick={()=>edit(id,'incoming',[...e.incoming,{id:crypto.randomUUID(),date,units:1,status:'open'}])}>Add incoming delivery</Button></fieldset></details></td></tr>;})}</tbody></table></div>
  <div className="restock-edit-area"><label className="check-row"><input type="checkbox" disabled={busy||!jobId} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>These stock details are correct for the products I still sell.</label><Button disabled={busy||!confirmed||!jobId} onClick={calculate}>{busy?'Calculating restock list…':Object.keys(plans).length?'Update restock list':'Calculate restock list'}</Button>{message&&<p role="status">{message}</p>}</div>
  <div className="restock-result-actions restock-edit-area"><Button variant="secondary" onClick={exportSheet}>Download restock sheet</Button><Button variant="secondary" onClick={()=>window.print()}>Print restock list</Button><Button variant="text" disabled={busy||!Object.keys(validPlans).length} onClick={async()=>{setBusy(true);try{await onSave(validPlans);setMessage('Restock list saved with this analysis.');}catch{setMessage('Could not save. Download the sheet to keep a copy.');}finally{setBusy(false);}}}>Save list</Button></div>
 </section>;
}
