import {useState, useRef, useEffect} from 'react';
import {createPortal} from 'react-dom';
import {Button, Notice} from './UI';
import {post, csv, download, friendlyDate, num, type Plan, type Result} from './data';
import BulkInventory, {type InventoryDraft} from './BulkInventory';

type Entry = {stock:string; lead:string; pack:string; minimum:string; incoming:InventoryDraft['incoming']};
export default function StoreRestock({result,jobId,saved,onSave,onAddData}:{result:Result;jobId:string|null;saved:Record<string,Plan>;onSave:(plans:Record<string,Plan>)=>Promise<void>;onAddData:()=>void}) {
 const [date,setDate]=useState(result.forecast_start),[lead,setLead]=useState('5'),[days,setDays]=useState('7'),[buffer,setBuffer]=useState('2');
 const [entries,setEntries]=useState<Record<string,Entry>>(()=>Object.fromEntries(result.products.map(p=>{const a=saved[p.product_id]?.assumptions;return [p.product_id,{stock:String(a?.stock ?? (result.quality.config.synthetic?20:'')),lead:String(a?.lead_days ?? ''),pack:String(a?.pack_size ?? 1),minimum:String(a?.minimum_order ?? 0),incoming:(a?.incoming as Entry['incoming'])||[]}];})));
 const [plans,setPlans]=useState(saved),[errors,setErrors]=useState<Record<string,string>>({}),[dirty,setDirty]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState('');
 const [detailId,setDetailId]=useState<string|null>(null);
 const dialogRef=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(detailId && dialogRef.current && !dialogRef.current.open) dialogRef.current.showModal();},[detailId]);
 const changed=(id?:string)=>{setDirty(new Set(id?[...dirty,id]:result.products.map(p=>p.product_id)));setConfirmed(false);setMessage('');};
 const edit=(id:string,k:keyof Entry,v:unknown)=>{setEntries(prev=>({...prev,[id]:{...prev[id],[k]:v}}));changed(id);};
 function status(id:string,eligible:boolean|undefined) {if(dirty.has(id)&&plans[id])return 'Recalculate to update';if(errors[id])return errors[id];if(!eligible)return 'Forecast needs more reliable data';if(entries[id].stock.trim()==='')return 'Add stock count';if(!plans[id])return 'Ready to calculate';return plans[id].pre_arrival_unmet_units>0?'May run out before delivery':plans[id].suggested_order_units>0?'Restock needed':'No order needed';}
 async function calculate(){setBusy(true);setMessage('');const next:Record<string,Plan>={};const problems:Record<string,string>={};try{for(const p of result.products){const e=entries[p.product_id];if(!p.inventory_eligible)continue;if(!e.stock.trim()){problems[p.product_id]='Add stock count';continue;}try{next[p.product_id]=await post<Plan>(`/jobs/${jobId}/inventory`,{product_id:p.product_id,stock:Number(e.stock),snapshot_date:date,lead_days:Number(e.lead||lead),review_days:Number(days),buffer_days:Number(buffer),pack_size:Number(e.pack),minimum_order:Number(e.minimum),incoming:e.incoming,mode:'historical_replay',confirmed:true});}catch(error){problems[p.product_id]=(error as Error).message;}}setPlans(next);setErrors(problems);setDirty(new Set());setMessage(`${Object.keys(next).length} products calculated. Check any rows that need attention.`);}finally{setBusy(false);}}
 const ordered=[...result.products].sort((a,b)=>(plans[b.product_id]?.pre_arrival_unmet_units||0)-(plans[a.product_id]?.pre_arrival_unmet_units||0)||(plans[b.product_id]?.suggested_order_units||0)-(plans[a.product_id]?.suggested_order_units||0));
 const validPlans=Object.fromEntries(Object.entries(plans).filter(([id])=>!dirty.has(id)));
 const canExport=!busy && dirty.size===0 && Object.keys(validPlans).length>0;
 const printPlan=()=>{if(canExport) window.print();};
 function exportSheet(){if(!canExport)return;download(`restock-list-${result.forecast_start}.csv`,csv([['Product','Product ID','You have (units)','Buy this many more (units)','Expected arrival','Notes','Plan date','Delivery days','Days after delivery','Extra days'],...ordered.map(p=>{const plan=validPlans[p.product_id];return [p.name,p.product_id,entries[p.product_id].stock,plan?.suggested_order_units??'',plan && plan.suggested_order_units > 0 ? friendlyDate(plan.arrival_date):'',status(p.product_id,p.inventory_eligible),friendlyDate(plan?.planning_date||date),plan?.assumptions.lead_days??(entries[p.product_id].lead||lead),plan?.assumptions.review_days??days,plan?.assumptions.buffer_days??buffer];})]));}
 return <section className="store-restock">
  <div className="restock-heading"><h2>Your store’s restock list</h2><p className="muted">Enter what you have. We’ll calculate how many more units to buy.</p></div>
  {!jobId&&<Notice>Saved results are shown below. Upload the sales files again to calculate a new plan.</Notice>}
  {result.quality.config.synthetic&&<Notice>Example stock counts are filled in. Change them to explore different plans.</Notice>}
  <div className="restock-edit-area">
  {jobId&&<fieldset disabled={busy} className="restock-fields"><BulkInventory jobId={jobId} onImport={items=>{if(Object.values(items).some(v=>v.snapshot_date!==date)) throw Error('The stock file date must match the stock count date shown above.');setEntries(prev=>{const next={...prev};for(const [id,v] of Object.entries(items)){if(next[id])next[id]={stock:String(v.stock??''),lead:String(v.lead_days??''),pack:String(v.pack_size??1),minimum:String(v.minimum_order??0),incoming:v.incoming||[]};}return next;});changed();setMessage('Stock counts imported. Check the table before calculating.');}}/></fieldset>}
  <p className="stock-date-note">This forecast starts on <strong>{friendlyDate(result.forecast_start)}</strong>. Use stock counts from that date. {result.forecast_start<new Date().toISOString().slice(0,10)&&<button className="text-link" onClick={onAddData}>Upload recent sales for a current plan</button>}</p>
  <fieldset disabled={busy||!jobId} className="restock-fields"><div className="inventory-grid">
   <label className="field">Stock counted on<input type="date" value={date} onChange={e=>{setDate(e.target.value);changed();}}/></label>
   <label className="field">Delivery takes (days)<input type="number" min="1" value={lead} onChange={e=>{setLead(e.target.value);changed();}}/></label>
   <label className="field">How many days should the stock last?<input type="number" min="1" value={days} onChange={e=>{setDays(e.target.value);changed();}}/></label>
  </div><details className="quiet-details"><summary>More options</summary><label className="field">Extra days of stock<input type="number" min="0" value={buffer} onChange={e=>{setBuffer(e.target.value);changed();}}/></label></details></fieldset></div>

  <div className="table-scroll"><table className="restock-table"><thead><tr><th>Product</th><th>You have</th><th>Order more</th><th>Expected arrival</th></tr></thead>
  <tbody>{ordered.map(p=>{const id=p.product_id,e=entries[id],plan=validPlans[id];return <tr key={id}>
    <td><strong>{p.name}</strong><button className="text-link restock-detail-link" onClick={()=>setDetailId(id)} aria-label={`Details for ${p.name}`}>Details</button>
    {plan && plan.pre_arrival_unmet_units > 0 && <p className="stock-shortage">May run out{plan.first_shortfall_date ? ` on ${friendlyDate(plan.first_shortfall_date)}` : ''}, before delivery.</p>}</td>
    <td><input aria-label={`Stock for ${p.name}`} type="number" min="0" step="1" disabled={busy||!jobId} value={e.stock} placeholder="Count" onChange={ev=>edit(id,'stock',ev.target.value)}/></td>
    <td>{plan ? <strong className={plan.suggested_order_units>0?'restock-amount':'muted'}>{plan.suggested_order_units>0?`${num(plan.suggested_order_units)} units`:'No order needed'}</strong>:<span className="muted">{status(id,p.inventory_eligible)}</span>}</td>
    <td>{plan && plan.suggested_order_units>0?friendlyDate(plan.arrival_date):'—'}</td>
  </tr>;})}</tbody></table></div>
  {detailId && (()=>{const id=detailId,e=entries[id],plan=validPlans[id],product=result.products.find(p=>p.product_id===id)!;return <dialog ref={dialogRef} className="restock-dialog" onClose={()=>setDetailId(null)}>
    <div className="restock-dialog-heading"><div><h2>{product.name}</h2><p className="muted">Product ID: {id}</p></div><Button variant="secondary" onClick={()=>dialogRef.current?.close()}>Close</Button></div>
    {plan ? <><h3>Why this amount?</h3><dl className="restock-breakdown">
    <dt>Expected stock at arrival</dt><dd>{plan.stock_before_new_order_on_arrival===undefined?'Not available':num(plan.stock_before_new_order_on_arrival)}</dd>
    <dt>Sales for {String(plan.assumptions.review_days ?? days)} days after arrival</dt><dd>{plan.protection_units===undefined?'Not available':num(plan.protection_units)}</dd>
    <dt>Extra stock</dt><dd>{num(plan.buffer_units)}</dd><dt>Order more</dt><dd><strong>{num(plan.suggested_order_units)} units</strong></dd></dl>
    {plan.pre_arrival_unmet_units>0&&<p className="stock-shortage">May run out before delivery. About {num(plan.pre_arrival_unmet_units)} units of demand may go unmet.</p>}
    <p className="muted">Incoming deliveries are counted on their arrival dates. Pack sizes and minimum orders apply when set.</p></>:<p>{status(id,product.inventory_eligible)}</p>}
    <h3>Product settings</h3>
    <fieldset disabled={busy||!jobId} className="restock-fields">{(['lead','pack','minimum'] as const).map(k=><label className="field" key={k}>{k==='lead'?'Delivery days (blank uses shared setting)':k==='pack'?'Units per pack':'Minimum order'}<input type="number" min={k==='minimum'?0:1} value={e[k]} onChange={ev=>edit(id,k,ev.target.value)}/></label>)}<p>Stock already on its way</p>{e.incoming.map((o,i)=><div key={i}><label className="field">Arrival date<input type="date" value={o.date} onChange={ev=>edit(id,'incoming',e.incoming.map((x,j)=>j===i?{...x,date:ev.target.value}:x))}/></label><label className="field">Units<input type="number" min="1" value={o.units} onChange={ev=>edit(id,'incoming',e.incoming.map((x,j)=>j===i?{...x,units:Number(ev.target.value)}:x))}/></label><span>{o.status}</span><Button variant="text" onClick={()=>edit(id,'incoming',e.incoming.filter((_,j)=>j!==i))}>Remove</Button></div>)}<Button variant="text" onClick={()=>edit(id,'incoming',[...e.incoming,{id:crypto.randomUUID(),date,units:1,status:'open'}])}>Add incoming delivery</Button></fieldset>
    <p className="muted">After editing, close this panel and update the restock list.</p>
  </dialog>;})()}
  <div className="restock-edit-area"><label className="check-row"><input type="checkbox" disabled={busy||!jobId} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>These stock details are correct for the products I still sell.</label><Button disabled={busy||!confirmed||!jobId} onClick={calculate}>{busy?'Calculating restock list…':Object.keys(plans).length?'Update restock list':'Calculate restock list'}</Button>{message&&<p role="status">{message}</p>}</div>
  <div className="restock-ready restock-edit-area"><p>{dirty.size>0?'Update the restock list before printing.':canExport?(Object.keys(validPlans).length===result.products.length?'Your restock list is ready.':'Your restock list is ready. Some products still need attention.'):'Calculate your list to download or print it.'}</p>
  <div className="restock-result-actions"><Button variant="secondary" className="restock-print-button" disabled={!canExport} onClick={printPlan}>Print restock list</Button><Button variant="text" disabled={!canExport} onClick={exportSheet}>Download spreadsheet</Button><Button variant="text" disabled={!canExport} onClick={async()=>{setBusy(true);try{await onSave(validPlans);setMessage('Restock list saved with this analysis.');}catch{setMessage('Could not save. Download the sheet to keep a copy.');}finally{setBusy(false);}}}>Save list</Button></div></div>
  {createPortal(<article className="restock-print" aria-hidden="true">
    <h1>Restock list</h1><p>Forecast: {friendlyDate(result.forecast_start)} – {friendlyDate(result.forecast_end)}</p>
    <p>Arrival dates assume orders are placed on each product’s stock count date below. They are estimates, not confirmed deliveries.</p>
    {!canExport?<p>Update the restock list before printing.</p>:<>
    <table><thead><tr><th>✓</th><th>Product</th><th>You have</th><th>Order more</th><th>Expected arrival</th></tr></thead><tbody>{ordered.map(p=>{const plan=validPlans[p.product_id];return <tr key={p.product_id}><td>□</td><td>{p.name}<small>{p.product_id}</small></td><td>{entries[p.product_id].stock||'—'}</td><td>{plan?(plan.suggested_order_units>0?`${num(plan.suggested_order_units)} units`:'No order needed'):status(p.product_id,p.inventory_eligible)}</td><td>{plan&&plan.suggested_order_units>0?friendlyDate(plan.arrival_date):'—'}</td></tr>;})}</tbody></table>
    {ordered.some(p=>!validPlans[p.product_id]||validPlans[p.product_id].pre_arrival_unmet_units>0)&&<section><h2>Needs attention</h2><ul>{ordered.map(p=>{const plan=validPlans[p.product_id];return !plan?<li key={p.product_id}>{p.name}: {status(p.product_id,p.inventory_eligible)}</li>:plan.pre_arrival_unmet_units>0?<li key={p.product_id}>{p.name}: may run out {plan.first_shortfall_date?`on ${friendlyDate(plan.first_shortfall_date)}`:'before delivery'}. About {num(plan.pre_arrival_unmet_units)} units short before arrival on {friendlyDate(plan.arrival_date)}.</li>:null;})}</ul></section>}
    <h2>Order breakdown · units</h2><table><thead><tr><th>Product</th><th>Stock at arrival</th><th>Sales after arrival</th><th>Extra stock</th><th>Order more</th></tr></thead><tbody>{ordered.map(p=>{const plan=validPlans[p.product_id];return plan?<tr key={p.product_id}><td>{p.name}</td><td>{plan.stock_before_new_order_on_arrival===undefined?'—':num(plan.stock_before_new_order_on_arrival)}</td><td>{plan.protection_units===undefined?'—':num(plan.protection_units)}</td><td>{num(plan.buffer_units)}</td><td>{num(plan.suggested_order_units)}</td></tr>:null;})}</tbody></table>
    <h2>Planning details</h2><table><thead><tr><th>Product</th><th>Stock counted</th><th>Delivery days</th><th>Days after arrival</th><th>Extra days</th></tr></thead><tbody>{ordered.map(p=>{const plan=validPlans[p.product_id];return plan?<tr key={p.product_id}><td>{p.name}</td><td>{friendlyDate(plan.planning_date)}</td><td>{String(plan.assumptions.lead_days??'—')}</td><td>{String(plan.assumptions.review_days??'—')}</td><td>{String(plan.assumptions.buffer_days??'—')}</td></tr>:null;})}</tbody></table>
    {ordered.some(p=>{const a=validPlans[p.product_id]?.assumptions;return a&&(Number(a.pack_size)>1||Number(a.minimum_order)>0||(a.incoming as Entry['incoming']||[]).length>0);})&&<section><h2>Special settings</h2>{ordered.map(p=>{const a=validPlans[p.product_id]?.assumptions;if(!a)return null;const incoming=a.incoming as Entry['incoming']||[];if(!(Number(a.pack_size)>1||Number(a.minimum_order)>0||incoming.length))return null;return <div key={p.product_id}><strong>{p.name}</strong>{Number(a.pack_size)>1&&<p>Pack size: {String(a.pack_size)} units.</p>}{Number(a.minimum_order)>0&&<p>Minimum order: {String(a.minimum_order)} units.</p>}{incoming.map((o,i)=><p key={i}>Existing delivery: {num(o.units)} units on {friendlyDate(o.date)} ({o.status}).</p>)}</div>;})}</section>}
    <p className="restock-print-note">Suggested quantities are based on estimated sales. Incoming deliveries and pack requirements may affect the calculation. No orders have been placed.</p>
    </>}
  </article>,document.body)}
 </section>;
}
